### ISSUE TITLE
core dump when running elisa-chat

### ISSUE THREAD

**Issue by oatmealm** [s-kostyaev/elisa#10]
Indexing seem to have worked. ```elisa-chat``` crashes emacs though:

```
emacs --debug-init

....

terminate called after throwing an instance of 'faiss::FaissException'
  what():  Error in virtual void faiss::IndexFlat::search(faiss::idx_t, const float*, faiss::idx_t, float*, faiss::idx_t*, const faiss::SearchParameters*) const at /home/runner/work/sqlite-vss/sqlite-vss/vendor/faiss/faiss/IndexFlat.cpp:34: Error: 'k > 0' failed
Fatal error 6: Aborted
Backtrace:
emacs(emacs_backtrace+0x5c)[0x5eb3cc]
emacs(terminate_due_to_signal+0xa1)[0x46fe74]
emacs[0x470c9b]
emacs[0x746374]
/lib64/libc.so.6(+0x3e9a0)[0x7fb0209089a0]
/lib64/libc.so.6(+0x90834)[0x7fb02095a834]
/lib64/libc.so.6(raise+0x1e)[0x7fb0209088ee]
/lib64/libc.so.6(abort+0xdf)[0x7fb0208f08ff]
/lib64/libstdc++.so.6(+0xa4d39)[0x7fb01eca4d39]
/lib64/libstdc++.so.6(+0xb4f6c)[0x7fb01ecb4f6c]
/lib64/libstdc++.so.6(+0xb4fd7)[0x7fb01ecb4fd7]
/lib64/libstdc++.so.6(+0xb5238)[0x7fb01ecb5238]
/home/xxx/.config/emacs/.local/cache/elisa/vss0.so(+0x99fd8)[0x7fb000499fd8]
/home/xxx.config/emacs/.local/cache/elisa/vss0.so(_ZNK5faiss18IndexIDMapTemplateINS_5IndexEE6searchElPKflPfPlPKNS_16SearchParametersE+0xef)[0x7fb00055c97f]
/home/xxx.config/emacs/.local/cache/vss0.so(+0xb6bff)[0x7faff5cb6bff]
/lib64/libsqlite3.so.0(+0x4b71c)[0x7fb020af771c]
/lib64/libsqlite3.so.0(sqlite3_step+0x533)[0x7fb020aeeb13]
emacs(Fsqlite_select+0x100)[0x70b490]
/home/xxx/.config/emacs/.local/cache/eln/29.2-623ad7f7/elisa-360ddd76-a4369ee8.eln(F656c6973612d66696e642d73696d696c6172_elisa_find_similar_0+0xd7)[0x7fb0009361f7]
emacs(Ffuncall+0xfd)[0x67072d]
/home/xxx/.config/emacs/.local/cache/eln/29.2-623ad7f7/elisa-360ddd76-a4369ee8.eln(F656c6973612d63686174_elisa_chat_0+0x42)[0x7fb000936bc2]
emacs(Ffuncall+0xfd)[0x67072d]
emacs(Ffuncall_interactively+0x3b)[0x66909b]
emacs(Ffuncall+0xfd)[0x67072d]
emacs(Fcall_interactively+0x19a9)[0x66aa59]
/usr/bin/../lib64/emacs/29.2/native-lisp/29.2-623ad7f7/preloaded/simple-fab5b0cf-9ff4140c.eln(F636f6d6d616e642d65786563757465_command_execute_0+0x285)[0x7fb01b5716b5]
emacs(Ffuncall+0xfd)[0x67072d]
/usr/bin/../lib64/emacs/29.2/native-lisp/29.2-623ad7f7/preloaded/simple-fab5b0cf-9ff4140c.eln(F657865637574652d657874656e6465642d636f6d6d616e64_execute_extended_command_0+0x1d9)[0x7fb01b570579]
emacs(Ffuncall+0xfd)[0x67072d]
emacs(Ffuncall_interactively+0x3b)[0x66909b]
emacs(Ffuncall+0xfd)[0x67072d]
emacs(Fapply+0x140)[0x672fe0]
emacs(Fcall_interactively+0x425)[0x6694d5]
/usr/bin/../lib64/emacs/29.2/native-lisp/29.2-623ad7f7/preloaded/simple-fab5b0cf-9ff4140c.eln(F636f6d6d616e642d65786563757465_command_execute_0+0x285)[0x7fb01b5716b5]
emacs(Ffuncall+0xfd)[0x67072d]
emacs[0x5c96be]
emacs(internal_condition_case+0x6e)[0x66d6ee]
emacs(command_loop_2+0x36)[0x5c89d6]
emacs(internal_catch+0x47)[0x66d647]
emacs[0x5c8e41]
emacs(recursive_edit_1+0xbf)[0x5c8f3f]
...
Aborted (core dumped)

```

**Comment by s-kostyaev** [comment]
Are you sure that indexing is done? I have no idea what happens, but k > 0 in error message looks interesting. It fails during similarity search. My best bet - you can try to make similarity search outside of emacs. You can see queries in Elisa source code. But you need to get embedding for that query. You can get it by calling llm-embedding with Elisa-embedding-provider.

**Comment by oatmealm** [comment]
No. You're right. It's empty....

![image](https://github.com/s-kostyaev/elisa/assets/68159077/7ac3d68e-9f07-4c1b-a78e-f25c2bdec822)

**Comment by oatmealm** [comment]
I can run ```(elisa-parse-info-manual "elisp")```  for example, and it seems to work. When I run ```(llm-embedding elis-embedding-provider content)``` where content is a buffer I passed in with ```buffer-substring-no-properties``` I can even see the vector values printed... so this works. Running```(elisa-parse-info-manual "elisp") ```  I can  see ```ollama``` spiking (i'm still in pure cpu mode)... so will let it finish and test if it worked.

**Comment by oatmealm** [comment]
Well, it finished but the db has not been populated. No error message either. Assuming ```elisa-parse-info-manual``` suppose to insert the embeddings.

**Comment by s-kostyaev** [comment]
> Assuming elisa-parse-info-manual suppose to insert the embeddings.

It's right assumption. Very strange to me.

**Comment by s-kostyaev** [comment]
@oatmealm for now update llm package and you will can user remote ollama. It may accelerate testing.

**Comment by oatmealm** [comment]
```llm``` seems to have been updated... tried again with remote ollama...  ```async-parse..``` seems to finish very quickly though I think it works? Answer though is wrong .... :)

![image](https://github.com/s-kostyaev/elisa/assets/68159077/4c3a9f00-2e52-48be-8d82-fdb4ab1e4117)

**Comment by oatmealm** [comment]
Update: I need to manually call ```elisa-parse-info-manual (xxxx)``` for it to be parsed it seems. Did it for ```eglot``` and now its added to the context.

![image](https://github.com/s-kostyaev/elisa/assets/68159077/0811f06f-62d0-4079-9da5-a7ea860eecb2)

**Comment by s-kostyaev** [comment]
> `llm` seems to have been updated... tried again with remote ollama... `async-parse..` seems to finish very quickly though I think it works?

Yep.

>  Answer though is wrong .... :)

LLMs hallucinate. With RAG should be better, but checking links is a good idea.

**Comment by s-kostyaev** [comment]
> Update: I need to manually call `elisa-parse-info-manual (xxxx)` for it to be parsed it seems. Did it for `eglot` and now its added to the context.

You can. But we have async parse commands for this.

**Comment by s-kostyaev** [comment]
@oatmealm should we close this?
