### ISSUE TITLE
Using llama3-chatqa

### ISSUE THREAD

**Issue by oatmealm** [s-kostyaev/elisa#16]
Hi there. This model sounds interesting. I was wondering if it's possible to simply swap fo the purpose of testing. I'm not getting any replies from the model so far. I'm assuing it might have a specilazed instruction set?

Its description:

A model from NVIDIA based on Llama 3 that excels at conversational question answering (QA) and retrieval-augmented generation (RAG).

**Comment by s-kostyaev** [comment]
Sure, this model looks very promising. I will definitely take a look. For now I'm trying to improve retrieving part of Elisa. You can see open PR.

**Comment by s-kostyaev** [comment]
I have done some testing. I'm not very impressed. This model doesn't follow my instructions. 
I'm impressed by gemma 2 9B, but it has some bugs in ollama for now (https://github.com/ollama/ollama/issues/5341).
