### ISSUE TITLE
https://elpa.gnu.org/packages/llm-0.3.0.tar: Not found

### ISSUE THREAD

**Issue by matteoredaelli** [s-kostyaev/elisa#2]
I got the error  
  "https://elpa.gnu.org/packages/llm-0.3.0.tar: Not found" 

with debian testing and GNU Emacs 29.1 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.38,  cairo version 1.16.0) of 2023-08-30, modified by Debian

after addinmg in my init.el file 
 
 (package-vc-install "https://github.com/s-kostyaev/elisa")
  
I checked the url "https://elpa.gnu.org/packages/llm-0.3.0.tar" and it is not found...

Regards
Matteo

**Comment by s-kostyaev** [comment]
Hi @matteoredaelli
Thank you for report this.
First of all, you need emacs 29.2 to run this package.
Second - try to install llm package by `M-x` `package-install` `llm` `RET`

**Comment by matteoredaelli** [comment]
Hello, 

OK I updated emacs to 29.2 thamks to Debian!

GNU Emacs 29.2 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.41,
 cairo version 1.18.0) of 2024-02-27, modified by Debian

But now I get
  File error: https://elpa.gnu.org/packages/async-1.9.7.tar, Not found

**Comment by s-kostyaev** [comment]
@matteoredaelli Elisa added to melpa. You can now install it by package-install from melpa.

**Comment by s-kostyaev** [comment]
Closing because there is simpler installation method
