### ISSUE TITLE
Database locked: ("database is locked" "database is locked" 5 5)

### ISSUE THREAD

**Issue by oatmealm** [s-kostyaev/elisa#21]
I'm guessing this is because the collection I'm querying is being parsed? I think there needs to a way to indicate what's happening?

```
error in process sentinel: Database locked: ("database is locked" "database is locked" 5 5)
```

**Comment by s-kostyaev** [comment]
In 1.0.4 added progress report for async operations. Don't start multiple parsing operations (web search also contains parsing) - sqlite can't handle concurrent writes. I have enabled `WAL` to be able to use read of already parsed collections and write during parsing of new collection.
