### ISSUE TITLE
Not enough data

### ISSUE THREAD

**Issue by oatmealm** [s-kostyaev/elisa#22]
I'm seeing this most of the time now. I'v deleted all the old sessions , created an empty session and added one .org file.  Also created a directory collection. I'm using the recommended model for Ollama.

```
#s(llm-ollama nil nil nil "http" "10.0.0.56" 11434 "gemma2:9b-instruct-q6_K" "chatfire/bge-m3:q8_0")
```

```
elisa-async-parse-directory done.
searching in collected data
async elisa processing done. [2 times]
Wrote /home/[xxx]/Nextcloud/ellama-sessions/Topic: Text analysis (gemma2:9b-instruct-q6_K).org
"Topic: Text analysis (gemma2:9b-instruct-q6_K).org" 125L, 4091C written
```

**Comment by s-kostyaev** [comment]
Are you sure that org file was already parsed when you did your test? Are you sure that file contains relevant information to answer your question? Can you share this file and your question?
I think "not enough data" is much better answer than hallucinations that's why I gave LLM this option.

**Comment by oatmealm** [comment]
Yes. I tried it again. I got an initial answer and then on a followup query with the same collection I'm getting not enough data. I'm also getting database is locked... and it stays locked until I restart emacs. 

Does it pre-process the org file btw? I'm seeing ellama-quote buffers the documents snippets which contain content from heading marked as "noexport"

**Comment by oatmealm** [comment]
Could elisa be parsing all my collections regardless of which one is currently active? I have couple of directory collections I'm not explicitly querying. 

UPDATE: I see now there's "elisa-enabled-collections" ...

**Comment by oatmealm** [comment]
Update. I disabled all collections and enabled one directory collection. Seem to work quite well...

**Comment by s-kostyaev** [comment]
@oatmealm can we close it now?
