### ISSUE TITLE
[issue] Database error: "Module name not on allowlist"

### ISSUE THREAD

**Issue by oatmealm** [s-kostyaev/elisa#27]
I'm having problems getting elisa working. In Doom, I had to set `elisa-sqlite-vss-path` manually for it to be found, but then when elisa starts a session, I'm getting this error:

```
Database error: "Module name not on allowlist"
```

I'm not sure if it's because it's not finding the correct extension or if I need to enable it mysefl (which was not the case befor, afaik).

Ellama works find with same connection object:

```
(setq +llm-host "10.0.0.56")
(setq +llm-chat-model "smollm2:1.7b-instruct-q6_K")
(setq +llm-embeding-model "nomic-embed-text")
(setq +llm-chat-params '(("num_ctx . 8192")))
(setq +llm-provider (make-llm-ollama
                     :host +llm-host
                     :chat-model +llm-chat-model
                     :embedding-model +llm-embeding-model
                     :default-chat-non-standard-params +llm-chat-params
                     :default-chat-temperature 0.1))

```

and of course I have both `elisa-chat-provider` and elisa-embeddings-provider set (to this object).

**Comment by s-kostyaev** [comment]
What is your Emacs version?

**Comment by oatmealm** [comment]
it's 29.4 sorry forgot to mention

**Comment by s-kostyaev** [comment]
It's strange. My first bet was that you have unsupported version of emacs, but both extensions needed by Elisa are in allow list since emacs 29.2. Can you show value of elisa-sqlite-vss-path?

**Comment by oatmealm** [comment]
Well, this might be helpful... it's not set. I set it manually 

```
(setopt elisa-sqlite-vss-path "/home/xxx/.config/emacs/.local/cache/elisa")
```

**Comment by oatmealm** [comment]
Closing since it's been rescaled possibly after an upgrade
