### ISSUE TITLE
Error on create index

### ISSUE THREAD

**Issue by guilhermecomum** [s-kostyaev/elisa#3]
Hi, first of all congratulations for this package. I'm very excited to have emacs jarvis LOL.

I instaled the packge using elpaca, here the config:
```elisp
  (use-package elisa
    :ensure (elisa
             :type git :host github
             :repo "s-kostyaev/elisa"))
```
Seems the instalation works fine, but when I tried to build index i'm getting this error:

Begin parsing builtin manuals.
error in process sentinel: async-when-done: Cannot open load file: No such file or directory, elisa
error in process sentinel: Cannot open load file: No such file or directory, elisa

**Comment by s-kostyaev** [comment]
Hi @guilhermecomum
Thank you for report.
Try `M-x toggle-debug-on-error`, repeat and paste debugger output here.

**Comment by guilhermecomum** [comment]
Here is:
```elisp
Debugger entered--Lisp error: (file-missing "Cannot open load file" "No such file or directory" "elisa")
  async-handle-result(#<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_24> (async-signal (file-missing "Cannot open load file" "No such file or directory" "elisa")) #<buffer *emacs*>)
  async-when-done(#<process emacs> "finished\n")
```

**Comment by s-kostyaev** [comment]
@guilhermecomum try to reinstall it from branch `fix-elpaca-installation`.

**Comment by guilhermecomum** [comment]
It works, thank you :D

**Comment by s-kostyaev** [comment]
Now you can remove branch from package receipt.
