### ISSUE TITLE
podman can't build with cache instructions

### ISSUE THREAD

**Issue by oatmealm** [s-kostyaev/elisa#30]
'podman' seems to not support BuildKit instructions (if I understand correctly the feature you use for caching pip downloads) out of the box. Had to remove since 'podman build --format=docker .' didn't work either. 

https://docs.podman.io/en/latest/markdown/podman-build.1.html

**Comment by s-kostyaev** [comment]
Hi @oatmealm.
Are you sure it should be in this repo? I don't understand why podman and buildkit.

**Comment by oatmealm** [comment]
Sorry. Meant the reranker repo...
