### ISSUE TITLE
LLM request failed with code 400: Bad Request

### ISSUE THREAD

**Issue by artelse** [s-kostyaev/elisa#6]
Installed everything successfully, but get following error on `elisa-chat` or `elisa-download-sqlite-vss`:
```llm-request-sync-raw-output: LLM request failed with code 400: Bad Request (additional information: {"error":"llama runner: failed to load model '/usr/share/ollama/.ollama/models/blobs/sha256:970aa74c0a90ef7482477cf803618e776e173c007bf957f635f1015bfcfef0e6': this model may be incompatible with your version of Ollama. If you previously pulled this model, try updating it by running `ollama pull nomic-embed-text:latest`"})``` 
I have symlinked the `/use/share/ollama` directory to another partition with more space, but things installed fine.

**Comment by s-kostyaev** [comment]
Try to run in terminal:
```shell
ollama pull nomic-embed-text
```
And retry elisa

**Comment by artelse** [comment]
That's what I did as per the error message, but still same problem.

**Comment by s-kostyaev** [comment]
@artelse try this command in terminal:
```shell
curl -X POST http://localhost:11434/api/embeddings -d '{"model": "nomic-embed-text", "prompt":"test"}'
```

**Comment by artelse** [comment]
That yields the same error:
```
{"error":"llama runner: failed to load model '/usr/share/ollama/.ollama/models/blobs/sha256:970aa74c0a90ef7482477cf803618e776e173c007bf957f635f1015bfcfef0e6': this model may be incompatible with your version of Ollama. If you previously pulled this model, try updating it by running `ollama pull nomic-embed-text:latest`"}%
```
Could it be a permission error? user is in group ollama with read-write perms.

**Comment by s-kostyaev** [comment]
Maybe. I think you should open this bug in upstream (in ollama repo).

**Comment by artelse** [comment]
Solved:
I reinstalled Ollama `curl -fsSL https://ollama.com/install.sh | sh` 
Thanks for the help!
