### ISSUE TITLE
no such module: vss0

### ISSUE THREAD

**Issue by oatmealm** [s-kostyaev/elisa#8]
Switched to local ollama... apropos https://github.com/s-kostyaev/elisa/issues/7#issue-2200225780

I'm now seeing this:

```
Contacting host: github.com:443
Wrote /home/xxx/.config/emacs/.local/cache/elisa/sqlite-vss-v0.1.2.tar.gz
elisa--reopen-db: Database error: "no such module: vss0"
```

extensions downloaded and are saved in the elisa subdirectory, where the db is supposed to be built.... 

```
~/.config/emacs/.local/cache/elisa$ ls
elisa.sqlite  vector0.so  vss0.so
```

**Comment by s-kostyaev** [comment]
What returns this elisp snippet:
```elisp
(require 'elisa)
(file-exists-p (elisa--vss-path))
```
?

**Comment by s-kostyaev** [comment]
It's strange, because vss0 loads after vector0. So one of extensions loaded successfully. Try to redownload it.

**Comment by oatmealm** [comment]
I did. Also deleted the sub directory and started from scratch. Same error. Is the db initialization happens before the first call to ollam? I'm not seeing an error apropos the previous problem, so I'm assuming that's the order. Also, before changing to local ollama I didn't see this error (about the extension).

**Comment by s-kostyaev** [comment]
Try previous extensions release, please. I can't check it on Linux. One call to ollama happens during database initialization.

**Comment by oatmealm** [comment]
Ok. Went one release back of both vss and vector... same error...  ```(file-exists-p (elisa--vss-path))``` always returns ```t```

**Comment by s-kostyaev** [comment]
@oatmealm which emacs version do you have?

**Comment by oatmealm** [comment]
it's 29.2

For what its worth., when I try to manually load the extension with ```(sqlite-load-extension db "vss0.so"``` I'm getting nil (0). Manually loading ```vector0.so``` returns ```t```

I have a db object manually created with ```(setq db (sqlite-open "elisa.sqlite"))```

**Comment by s-kostyaev** [comment]
Try to load it with sqlite outside of emacs. If it doesn't work, it should be an issue in sqlite-vss repo. Could you make this experiment?

**Comment by oatmealm** [comment]
Good idea! It's a missing dependency on Fedora. Had to install ```blas``` and ```lapack-devel``` :) thanks !

**Comment by julian-hoch** [comment]
I have the same issue here on NixOS.  I get:

Debugger entered--Lisp error: (sqlite-error "no such module: vss0")
I installed both "blas" and "lapack", which did not help...
