### ISSUE TITLE
Erorr when calling elisa-async-parse-builtin-manuals: No such file or directory" "elisa"

### ISSUE THREAD

**Issue by oatmealm** [s-kostyaev/elisa#9]
I'm assuming that the error message if a failure to load the ```elisa``` library itself from within the async call ```elisa-async-parse-builtin-manuals```? 

```
Debugger entered--Lisp error: (file-missing "Cannot open load file" "No such file or directory" "elisa")
  async-handle-result(#<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_24> (async-signal (file-missing "Cannot open load file" "No such file or directory" "elisa")) #<buffer *emacs*>)
  async-when-done(#<process emacs> "finished\n")
```

**Comment by s-kostyaev** [comment]
How do you install Elisa?

**Comment by oatmealm** [comment]
In doom its installed using straight. Manually requiring seems to work.

**Comment by s-kostyaev** [comment]
If you will install it with package.el it will work. If you add path to Elisa to load-path manually, it will also work. Not sure how it works in doom.

**Comment by oatmealm** [comment]
Trying to install from MELPA instead source... btw, can you explain why package-initialize is required? Is it true to all async calls?

**Comment by oatmealm** [comment]
Ok, it works when I install the melpa version, but not current version in git it seems.

**Comment by s-kostyaev** [comment]
I use async package to prevent emacs lock during parsing. It starts emacs without user configuration with `emacs - q`. To be able to use functions from Elisa I share load-path variable with async environment.
